### PR TITLE
Added queue statistics

### PR DESCRIPTION
**Pull request by akempes**
Hi,

I really like your package. For a new project I needed a bit more details about the queue, therefor I've added some statistics:
* Total items in the queue (All (un)resolved items + items still in _queue list)
* Total items that are pending (all unresolved items + items still in _queue list)
* Boolean that will be true when all items in the queue are resolved

The statistics are accessible like this:
```js
var queue1 = $queueFactory(2);
console.log(queue1.queueTotal, queue1.queuePending, queue1.queueIdle);
```

I'm using this for a progress bar...

### CODE REVIEW

**Comment by pc035860** [comment]
Hi @akempes 

The statistics data seems to add some additional overhead to the queue. 
How about making it opt-in?

```js
// Create a queue with concurrent task quota of 2
var queue1 = $queueFactory(2);

// Create a deferred queue
var queue2 = $queueFactory(1, { defer: true });

// Create a queue with statistics
var queue3 = $queueFactory(1, { statistics: true });
```

**Comment by pc035860** [comment]
BTW, glad you like the package.

**Comment by akempes** [comment]
Thanks for your feedback. It now configurable.

**Comment by pc035860** [comment]
@akempes Sorry for the late response!

Thanks for the PR. I'll merge it and make some small tweaks. Glad that you like this module.

**Pull request merged**
